# (Dev-env) Install MATLAB Engine API
- [How to install MATLAB Engine API for Python](https://www.mathworks.com/help/matlab/matlab_external/install-the-matlab-engine-for-python.html#responsive_offcanvas)

In [1]:
import numpy as np
import pandas as pd
import os
from m_parser import * 
import matlab.engine

eng = matlab.engine.start_matlab()

# 1. 39 Bus

## 1.1. Load the dataset

In [2]:
# load the datasets
mpc = eng.case39()
case39_dict = read_m_data(mpc)

In [3]:
case39_dict

{'version': '2',
 'baseMVA': 100.0,
 'bus':     bus_i  type       Pd     Qd   Gs   Bs  area        Vm         Va  baseKV  \
 0     1.0   1.0    97.60   44.2  0.0  0.0   2.0  1.039384 -13.536602   345.0   
 1     2.0   1.0     0.00    0.0  0.0  0.0   2.0  1.048494  -9.785267   345.0   
 2     3.0   1.0   322.00    2.4  0.0  0.0   2.0  1.030708 -12.276384   345.0   
 3     4.0   1.0   500.00  184.0  0.0  0.0   1.0  1.004460 -12.626734   345.0   
 4     5.0   1.0     0.00    0.0  0.0  0.0   1.0  1.006006 -11.192339   345.0   
 5     6.0   1.0     0.00    0.0  0.0  0.0   1.0  1.008226 -10.408330   345.0   
 6     7.0   1.0   233.80   84.0  0.0  0.0   1.0  0.998397 -12.755626   345.0   
 7     8.0   1.0   522.00  176.6  0.0  0.0   1.0  0.997872 -13.335844   345.0   
 8     9.0   1.0     6.50  -66.6  0.0  0.0   1.0  1.038332 -14.178442   345.0   
 9    10.0   1.0     0.00    0.0  0.0  0.0   1.0  1.017843  -8.170875   345.0   
 10   11.0   1.0     0.00    0.0  0.0  0.0   1.0  1.013386  -8.936

In [4]:
case39_dict.keys()

dict_keys(['version', 'baseMVA', 'bus', 'gen', 'branch', 'gencost'])

In [5]:
case39_dict["baseMVA"]

100.0

In [6]:
case39_dict["bus"].tail()

bus_i  type      Pd     Qd   Gs   Bs  area      Vm         Va  baseKV  \
34   35.0   2.0     0.0    0.0  0.0  0.0   3.0  1.0494   1.776507   345.0   
35   36.0   2.0     0.0    0.0  0.0  0.0   3.0  1.0636   4.468437   345.0   
36   37.0   2.0     0.0    0.0  0.0  0.0   2.0  1.0275  -1.582899   345.0   
37   38.0   2.0     0.0    0.0  0.0  0.0   3.0  1.0265   3.892818   345.0   
38   39.0   2.0  1104.0  250.0  0.0  0.0   1.0  1.0300 -14.535256   345.0   

    zone  Vmax  Vmin  
34   1.0  1.06  0.94  
35   1.0  1.06  0.94  
36   1.0  1.06  0.94  
37   1.0  1.06  0.94  
38   1.0  1.06  0.94

In [7]:
case39_dict["gen"].tail()

bus      Pg         Qg   Qmax   Qmin      Vg  mBase  status    Pmax  Pmin  \
5  35.0   650.0  210.66100  300.0 -100.0  1.0494  100.0     1.0   687.0   0.0   
6  36.0   560.0  100.16500  240.0    0.0  1.0636  100.0     1.0   580.0   0.0   
7  37.0   540.0   -1.36945  250.0    0.0  1.0275  100.0     1.0   564.0   0.0   
8  38.0   830.0   21.73270  300.0 -150.0  1.0265  100.0     1.0   865.0   0.0   
9  39.0  1000.0   78.46740  300.0 -100.0  1.0300  100.0     1.0  1100.0   0.0   

   ...  Pc2  Qc1min  Qc1max  Qc2min  Qc2max  ramp_agc  ramp_10  ramp_30  \
5  ...  0.0     0.0     0.0     0.0     0.0       0.0      0.0      0.0   
6  ...  0.0     0.0     0.0     0.0     0.0       0.0      0.0      0.0   
7  ...  0.0     0.0     0.0     0.0     0.0       0.0      0.0      0.0   
8  ...  0.0     0.0     0.0     0.0     0.0       0.0      0.0      0.0   
9  ...  0.0     0.0     0.0     0.0     0.0       0.0      0.0      0.0   

   ramp_q  apf  
5     0.0  0.0  
6     0.0  0.0  
7     0.0  0.0  
8     0.0  0.0  
9     0.0  0.0  

[5 rows x 21 columns]

In [8]:
case39_dict["gencost"].tail()

2  startup  shutdown    n    c2   c1   c0
5  2.0      0.0       0.0  3.0  0.01  0.3  0.2
6  2.0      0.0       0.0  3.0  0.01  0.3  0.2
7  2.0      0.0       0.0  3.0  0.01  0.3  0.2
8  2.0      0.0       0.0  3.0  0.01  0.3  0.2
9  2.0      0.0       0.0  3.0  0.01  0.3  0.2

In [9]:
case39_dict["branch"].tail()

fbus  tbus       r       x       b   rateA   rateB   rateC  ratio  angle  \
41  26.0  27.0  0.0014  0.0147  0.2396   600.0   600.0   600.0  0.000    0.0   
42  26.0  28.0  0.0043  0.0474  0.7802   600.0   600.0   600.0  0.000    0.0   
43  26.0  29.0  0.0057  0.0625  1.0290   600.0   600.0   600.0  0.000    0.0   
44  28.0  29.0  0.0014  0.0151  0.2490   600.0   600.0   600.0  0.000    0.0   
45  29.0  38.0  0.0008  0.0156  0.0000  1200.0  1200.0  2500.0  1.025    0.0   

    status  angmin  angmax  
41     1.0  -360.0   360.0  
42     1.0  -360.0   360.0  
43     1.0  -360.0   360.0  
44     1.0  -360.0   360.0  
45     1.0  -360.0   360.0

## 1.2. Choose features and label

### Input as features
- Pg
- Pd
- Qd


- We will give some changes in these feature values in order to generate a dataset for GCN.
- How?: 
    - Pd & Qd: Monte-Carlo Sampling with uniform dist.
    - Pg: solving a power flow problem by [Matpower](https://matpower.org/)

In [15]:
Pg = case39_dict["gen"][["bus","Pg"]]
Pg

bus        Pg
0  30.0   250.000
1  31.0   677.871
2  32.0   650.000
3  33.0   632.000
4  34.0   508.000
5  35.0   650.000
6  36.0   560.000
7  37.0   540.000
8  38.0   830.000
9  39.0  1000.000

In [16]:
Pd = case39_dict["bus"][["bus_i", "Pd"]]
Pd

bus_i       Pd
0     1.0    97.60
1     2.0     0.00
2     3.0   322.00
3     4.0   500.00
4     5.0     0.00
5     6.0     0.00
6     7.0   233.80
7     8.0   522.00
8     9.0     6.50
9    10.0     0.00
10   11.0     0.00
11   12.0     8.53
12   13.0     0.00
13   14.0     0.00
14   15.0   320.00
15   16.0   329.00
16   17.0     0.00
17   18.0   158.00
18   19.0     0.00
19   20.0   680.00
20   21.0   274.00
21   22.0     0.00
22   23.0   247.50
23   24.0   308.60
24   25.0   224.00
25   26.0   139.00
26   27.0   281.00
27   28.0   206.00
28   29.0   283.50
29   30.0     0.00
30   31.0     9.20
31   32.0     0.00
32   33.0     0.00
33   34.0     0.00
34   35.0     0.00
35   36.0     0.00
36   37.0     0.00
37   38.0     0.00
38   39.0  1104.00

In [17]:
Qd = case39_dict["bus"][["bus_i", "Qd"]]
Qd

bus_i     Qd
0     1.0   44.2
1     2.0    0.0
2     3.0    2.4
3     4.0  184.0
4     5.0    0.0
5     6.0    0.0
6     7.0   84.0
7     8.0  176.6
8     9.0  -66.6
9    10.0    0.0
10   11.0    0.0
11   12.0   88.0
12   13.0    0.0
13   14.0    0.0
14   15.0  153.0
15   16.0   32.3
16   17.0    0.0
17   18.0   30.0
18   19.0    0.0
19   20.0  103.0
20   21.0  115.0
21   22.0    0.0
22   23.0   84.6
23   24.0  -92.2
24   25.0   47.2
25   26.0   17.0
26   27.0   75.5
27   28.0   27.6
28   29.0   26.9
29   30.0    0.0
30   31.0    4.6
31   32.0    0.0
32   33.0    0.0
33   34.0    0.0
34   35.0    0.0
35   36.0    0.0
36   37.0    0.0
37   38.0    0.0
38   39.0  250.0

### Output as labels
- loadings = (I_act / I_max) * 100 = (F_act / F_max) * 100

    - F_max
        - Read from the case data sheet.
    - F_act
        - Need to solve a power flow problem by [Matpower](https://matpower.org/)

In [75]:
F_max = case39_dict["branch"][["fbus", "tbus", "rateA", "rateB", "rateC"]]
F_max

fbus  tbus   rateA   rateB   rateC
0    1.0   2.0   600.0   600.0   600.0
1    1.0  39.0  1000.0  1000.0  1000.0
2    2.0   3.0   500.0   500.0   500.0
3    2.0  25.0   500.0   500.0   500.0
4    2.0  30.0   900.0   900.0  2500.0
5    3.0   4.0   500.0   500.0   500.0
6    3.0  18.0   500.0   500.0   500.0
7    4.0   5.0   600.0   600.0   600.0
8    4.0  14.0   500.0   500.0   500.0
9    5.0   6.0  1200.0  1200.0  1200.0
10   5.0   8.0   900.0   900.0   900.0
11   6.0   7.0   900.0   900.0   900.0
12   6.0  11.0   480.0   480.0   480.0
13   6.0  31.0  1800.0  1800.0  1800.0
14   7.0   8.0   900.0   900.0   900.0
15   8.0   9.0   900.0   900.0   900.0
16   9.0  39.0   900.0   900.0   900.0
17  10.0  11.0   600.0   600.0   600.0
18  10.0  13.0   600.0   600.0   600.0
19  10.0  32.0   900.0   900.0  2500.0
20  12.0  11.0   500.0   500.0   500.0
21  12.0  13.0   500.0   500.0   500.0
22  13.0  14.0   600.0   600.0   600.0
23  14.0  15.0   600.0   600.0   600.0
24  15.0  16.0   600.0   600.0   600.0
25  16.0  17.0   600.0   600.0   600.0
26  16.0  19.0   600.0   600.0  2500.0
27  16.0  21.0   600.0   600.0   600.0
28  16.0  24.0   600.0   600.0   600.0
29  17.0  18.0   600.0   600.0   600.0
30  17.0  27.0   600.0   600.0   600.0
31  19.0  20.0   900.0   900.0  2500.0
32  19.0  33.0   900.0   900.0  2500.0
33  20.0  34.0   900.0   900.0  2500.0
34  21.0  22.0   900.0   900.0   900.0
35  22.0  23.0   600.0   600.0   600.0
36  22.0  35.0   900.0   900.0  2500.0
37  23.0  24.0   600.0   600.0   600.0
38  23.0  36.0   900.0   900.0  2500.0
39  25.0  26.0   600.0   600.0   600.0
40  25.0  37.0   900.0   900.0  2500.0
41  26.0  27.0   600.0   600.0   600.0
42  26.0  28.0   600.0   600.0   600.0
43  26.0  29.0   600.0   600.0   600.0
44  28.0  29.0   600.0   600.0   600.0
45  29.0  38.0  1200.0  1200.0  2500.0

## 1.3. Create an input & output data sample

In [28]:
current_dir = os.getcwd()
os.chdir('./matpower7.1/')
eng = matlab.engine.start_matlab()
case_name = "case39.m"
dist_scale = 0.03

data = eng.run_opf_ac(case_name, dist_scale)

os.chdir(current_dir)

### Input data sample

In [54]:
 np.asarray(data['Pg'])

array([[677.73238704],
       [645.99999767],
       [677.06427599],
       [651.99999052],
       [507.99999945],
       [666.92840073],
       [579.99999899],
       [563.99999911],
       [659.79999269],
       [696.84068783]])

In [51]:
 np.asarray(data['Pd'])

array([[  96.02571062],
       [   0.        ],
       [ 318.92072778],
       [ 506.50388033],
       [   0.        ],
       [   0.        ],
       [ 228.71201477],
       [ 510.80712613],
       [   6.52420815],
       [   0.        ],
       [   0.        ],
       [   8.34645863],
       [   0.        ],
       [   0.        ],
       [ 317.17883392],
       [ 320.23153511],
       [   0.        ],
       [ 171.95590693],
       [   0.        ],
       [ 652.04590978],
       [ 274.84043291],
       [   0.        ],
       [ 253.92173339],
       [ 310.12644996],
       [ 216.6532547 ],
       [ 142.60143227],
       [ 291.23500668],
       [ 206.04232885],
       [ 290.0460086 ],
       [   0.        ],
       [   9.50058175],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [   0.        ],
       [1151.10909064]])

In [47]:
 np.asarray(data['Qd'])

array([[ 41.76826847],
       [  0.        ],
       [  2.49415356],
       [182.10871294],
       [  0.        ],
       [  0.        ],
       [ 84.15889828],
       [177.68591018],
       [-69.57641582],
       [  0.        ],
       [  0.        ],
       [ 83.69617884],
       [  0.        ],
       [  0.        ],
       [156.61362807],
       [ 33.41151093],
       [  0.        ],
       [ 28.70545774],
       [  0.        ],
       [108.28858573],
       [115.83299229],
       [  0.        ],
       [ 84.67627019],
       [-93.93623836],
       [ 45.62926901],
       [ 16.96054686],
       [ 78.02207918],
       [ 26.3309821 ],
       [ 26.6002973 ],
       [  0.        ],
       [  4.59550707],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [246.33854568]])

In [66]:
feature = np.hstack((np.asarray(data['Pg']).squeeze(),
                    np.asarray(data['Pd']).squeeze(), 
                    np.asarray(data['Qd']).squeeze()))

feature = np.expand_dims(feature, axis=1)
feature

array([[ 677.73238704],
       [ 645.99999767],
       [ 677.06427599],
       [ 651.99999052],
       [ 507.99999945],
       [ 666.92840073],
       [ 579.99999899],
       [ 563.99999911],
       [ 659.79999269],
       [ 696.84068783],
       [  96.02571062],
       [   0.        ],
       [ 318.92072778],
       [ 506.50388033],
       [   0.        ],
       [   0.        ],
       [ 228.71201477],
       [ 510.80712613],
       [   6.52420815],
       [   0.        ],
       [   0.        ],
       [   8.34645863],
       [   0.        ],
       [   0.        ],
       [ 317.17883392],
       [ 320.23153511],
       [   0.        ],
       [ 171.95590693],
       [   0.        ],
       [ 652.04590978],
       [ 274.84043291],
       [   0.        ],
       [ 253.92173339],
       [ 310.12644996],
       [ 216.6532547 ],
       [ 142.60143227],
       [ 291.23500668],
       [ 206.04232885],
       [ 290.0460086 ],
       [   0.        ],
       [   9.50058175],
       [   0.   

### Output data sample

In [68]:
F_act = np.asarray(data['F_act'])

In [76]:
F_max = np.asarray(F_max["rateA"])
F_max = np.expand_dims(F_max, axis=1)

In [80]:
label = (F_act / F_max) * 100
label

array([[-64.04261616],
       [ 28.82299863],
       [ 89.60737786],
       [-31.87024686],
       [-75.30359856],
       [ 25.20483827],
       [  0.14559445],
       [-17.98116606],
       [-54.5606069 ],
       [-43.17957691],
       [ 45.5724282 ],
       [ 56.31112406],
       [-81.03638923],
       [-35.36107866],
       [ 30.73449181],
       [ 19.37714247],
       [ 18.56693537],
       [ 64.95468268],
       [ 47.88936332],
       [-75.229364  ],
       [  0.16484285],
       [ -1.83413458],
       [ 46.30013392],
       [  0.62414668],
       [-52.24467392],
       [ 44.02405236],
       [-83.11600032],
       [-57.84690299],
       [ -8.82487609],
       [ 28.56938328],
       [ 15.37930659],
       [ 16.29302188],
       [-72.10808468],
       [-56.17347527],
       [-69.20200452],
       [  6.87287731],
       [-74.10315564],
       [ 60.95988905],
       [-64.27624691],
       [ 30.73057174],
       [-62.46722352],
       [ 33.26950172],
       [ -9.08535589],
       [-17

---

# 2. Texas

## Load the dataset

In [11]:
# set the dataset file path
dataset_dir = "../data/Texas 2000 - June 2016 Synthetic Case"
dataset_name = "Texas2000_June2016.xlsx"

dataset_path = os.path.join(dataset_dir, dataset_name)

In [12]:
xl = pd.ExcelFile(dataset_path)
xl.sheet_names

['Areas',
 'Substations',
 'Buses',
 'Lines',
 'Transformers',
 'Loads',
 'Generators',
 'Shunts',
 'Benchmark Power Flow Solution']

## Choose features and label

### Input as feature data
- P_gen
- P_load
- Q_load

In [17]:
xl.parse('Generators')

Bus Number  Min MW  Max MW  Min Mvar  Max Mvar  MW dispatch, default  \
0             1  729.00  2430.0   -199.26    894.24               2150.61   
1          1502   91.38   304.6    -19.49    170.58                161.77   
2          1503   70.80   236.0    -15.10    132.16                125.34   
3          1504   52.92   176.4    -11.29     98.78                 93.68   
4          1505  114.21   380.7    -24.36    213.19                202.19   
..          ...     ...     ...       ...       ...                   ...   
277        1778    1.92     6.4     -0.71      3.26                  2.16   
278        1779  279.60   932.0   -113.70    434.31                314.74   
279        1780  167.70   559.0    -35.78    313.04                217.88   
280        1781    1.83     6.1     -0.39      3.42                  2.38   
281        1782   45.75   152.5     -9.76     85.40                 59.44   

     Voltage Set Point  
0                 1.04  
1                 1.04  
2                 1.04  
3                 1.04  
4                 1.04  
..                 ...  
277               1.04  
278               1.04  
279               1.01  
280               1.01  
281               1.01  

[282 rows x 7 columns]

In [20]:
P_gens = xl.parse('Generators')["MW dispatch, default"]

In [23]:
xl.parse('Loads')

Bus Number      MW   Mvar
0              2  249.85  71.21
1              3  153.92  43.87
2              4  183.21  52.22
3              5  125.84  35.87
4              6   21.42   6.10
...          ...     ...    ...
1412        1414    1.72   0.49
1413        1415    1.48   0.42
1414        1416    0.39   0.11
1415        1417    4.33   1.23
1416        1418    0.00   0.00

[1417 rows x 3 columns]

In [24]:
P_loads = xl.parse('Loads')["MW"]
Q_loads = xl.parse('Loads')["Mvar"]

### Output as label data
- loadings = (I_act * 100) / I_max  

In [25]:
xl.parse('Lines')

From Bus Number  To Bus Number  Circuit Number    R, pu    X, pu  \
0                   2              4               1  0.00217  0.01199   
1                   2             39               1  0.00147  0.00996   
2                   2            112               1  0.00097  0.00640   
3                   2            115               1  0.00101  0.00641   
4                   3             13               1  0.00149  0.01570   
...               ...            ...             ...      ...      ...   
2476             1979           1980               1  0.00015  0.00159   
2477             1988           1983               1  0.00058  0.00710   
2478             1985           1994               1  0.00339  0.03757   
2479             1998           1985               1  0.00708  0.06803   
2480             1988           1999               1  0.00102  0.01243   

        B, pu   MVA Limit  
0     0.11458   207.35247  
1     0.19333   383.83112  
2     0.12818   310.13236  
3     0.00892   207.55165  
4     0.19691   367.89625  
...       ...         ...  
2476  0.02675  1207.06625  
2477  0.12141  1326.57776  
2478  0.77439  1326.57776  
2479  1.37771  1207.06625  
2480  0.21254  1326.57776  

[2481 rows x 7 columns]

In [26]:
I_max = xl.parse('Lines')["MVA Limit"]